### ISSUE TITLE
Lot of console.logs

### ISSUE THREAD

**Issue by ronaldohoch** [matterport/showcase-sdk-tutorial#1]
Hello!

Is there a way to remove these console log's from Matterport embed?
![image](https://user-images.githubusercontent.com/2287371/71089550-de28cb00-217f-11ea-9c90-9893d4411ce5.png)

Thank you

**Comment by gbruce** [comment]
You can append `&log=0` to the embed url.
e.g. https://my.matterport.com/show?m=22Ub5eknCVx&play=1&qs=1&log=0

**Comment by ronaldohoch** [comment]
@gbruce It works!
Thank you!

**Comment by ChetanTechnource** [comment]
@ronaldohoch 

It's not resolved. It is still loggin error in console logs tab. 

`https://my.matterport.com/show?m=22Ub5eknCVx&play=1&qs=1&log=0&mls=1
`
[Google Drive Screenshot](https://drive.google.com/file/d/1fWPHSzI6qPTB_UzqZ0m0UMaboSyesZyQ/view?usp=sharing)
